window.onunload=function(){};
function Track(a,b,c,d){void 0===a&&(a="pi");void 0===b&&(b=GetMetaContent("section"));void 0===c&&(c=GetMetaContent("contentposition"));void 0===d&&0==d;var e=GetClickPos();var f="pi"==a?GetEventPosition():!1;a={lib:{parameter:{software:"dita",softwareversion:GetMetaContent("version").substring(0,8),brand:GetBrand(),trackingtype:a,destination:GetLanguage()}}};"notfounderrorpage"==GetMetaContent("DC.Identifier")?(a.lib.parameter.section="help.error.view",a.lib.parameter.result="23000404"):(b&&(a.lib.parameter.section=
b),c&&(a.lib.parameter.contentposition=c));d&&!ContainsPersonalData(d.query)&&(a.lib.parameter.count=d.numFound);f&&(a.lib.parameter.eventposition=f);e&&(a.lib.parameter.count=e);(new TrackLib(a)).track()}function ContainsPersonalData(a){return!0}function HasLinkType(a){a=a||location.hash.substr(1);return a.match(/((faq|text|index)link|teasericon|searchterm|topmenu|breadcrumb)/g)?!0:!1}
function GetEventPosition(){var a=GetMetaContent("section");a=isSearchPage(a)?BuildHash("searchterm"):location.hash.substr(1);if(HasLinkType(a)){if(-1<a.indexOf("&")){a=a.split("&");var b=a.length;for(var c=0;c<b;c++)if(-1<a[c].indexOf("searchterm_"))return a[c];return!1}return a}return!1}function GetMetaContent(a){return(a=document.querySelector('meta[name="'+a+'"]'))?a.getAttribute("content"):!1}
function GetBrand(){var a;if(a=GetMetaContent("brand"))return a;a=window.location.host;a=a.replace(/(hilfe|support)(\-pre|\-qa)?\./g,"");return a=a.replace(".","")}function isIndexPage(){var a=GetMetaContent("contentposition");return 0==a||0>a.indexOf(".")?!0:!1}function isSearchPage(a){return a?a.match(/help\.(suche|searchresults)\.view/g)?!0:!1:!1}
function GetSearchTerm(){if("undefined"!==typeof meta)var a=meta.query;else{a=window.location.hash;if(""==a)return!1;var b=a.indexOf("q=");if(-1!==b)a=a.substring(b+2);else if(-1!==window.location.href.indexOf("/searchresults/searchresult.html")||-1!==window.location.href.indexOf("/suche/index.html"))a=a.substring(1),a=a.replace(/(\?|\&)?(r|p|pos)=[0-9]*/,"");else return!1}return ContainsPersonalData(a)?!1:""==a?!1:a}function GetSearchHits(a){return"undefined"!==typeof a?a.hits:!1}
function GetClickPos(){var a=window.location.search.substring(1);""==a&&(a=window.location.hash);if(""==a)return!1;a=a.split("&");for(var b=0;b<a.length;b++){var c=a[b].split("=");if(""!=c[1]&&("p"==c[0]||"#p"==c[0]||"pos"==c[0]||"#pos"==c[0]))return c[1]}return!1}function GetLanguage(){var a=window.location.hostname;var b=a.lastIndexOf(".");switch(a.substring(b+1)){case "de":case "net":return"de";case "com":return"en";case "fr":return"fr";case "es":return"es";default:return!1}}
function AppendToHash(a,b){var c=0>a.indexOf("#")?"#":"&";return a+c+b}function BuildHash(a){if(-1=="faqlink teasericon textlink indexlink searchterm topmenu breadcrumb".split(" ").indexOf(a))return!1;var b=a;var c=GetMetaContent("section");var d=GetMetaContent("contentposition");var e=GetSearchTerm();d&&(d=d.replace(".","_"));c&&(c=c.replace(/\.view$/,""),c=c.replace(".","_"));"topmenu"==a?b="topmenu":"searchterm"==a&&e&&(b=b+"_"+e);c&&(b=b+"_"+c);d&&(b=b+"_"+d);return b}
function AppendHashToLinkAndFollow(a,b,c){b=BuildHash(b);c.preventDefault();c=a.attr("href");a.attr("href",AppendToHash(c,b));window.location=a.attr("href")}$(".teaser").on("click",function(a){AppendHashToLinkAndFollow($(this),"teasericon",a)});$(".xref").not(".external").on("click",function(a){var b=isIndexPage()?"indexlink":"textlink";AppendHashToLinkAndFollow($(this),b,a)});$(".faqlink").on("click",function(a){AppendHashToLinkAndFollow($(this),"faqlink",a)});
$(".breadcrumb").on("click",function(a){AppendHashToLinkAndFollow($(this),"breadcrumb",a)});$(".navColumn li a").on("click",function(a){AppendHashToLinkAndFollow($(this),"topmenu",a)});$(".video").on("play",function(a){0==$(this)[0].currentTime&&(a=GetMetaContent("section").replace(".view",".video.view"),Track("ev",a))});$(".topmenu").on("click",function(a){a=$(this).text();Track("cl","help.topmenu.start",a)});
$(".contactTitle").one("click",function(a){a=GetMetaContent("section").replace("help.","").replace(".view","");Track("cl","help."+a+".contact-us.start")});$(document).ready(function(){var a=GetMetaContent("section");0==isSearchPage(a)&&Track("pi",a);NSfTIF.track({brand:GetMetaContent("tropproduct"),deviceclass:detectmob(),pageidentifier:GetMetaContent("troppageidentifier"),region:GetMetaContent("tropregion"),frabo:!1})});
